engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
  - scripts/**
  - app.js
  - index.js
exclude_paths:
- test/**/*
- node_modules
