language: node_js
node_js:
- "4.6.0"
cache:
  directories:
  - node_modules
sudo: false
before_script:
- psql -c 'create database continua11y-dashboard-test;' -U postgres
script: npm run test_coverage
after_script:
- codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
services:
  - postgresql
env:
  global:
  - DATABASE_USER_NAME=postgres
  - GITHUB_TOKEN=FAKE_TEST_TOKEN
  - NODE_ENV=test
  - CONTINUA11Y_URL=https://continua11y-staging.apps.cloud.gov
