language: node_js
node_js:
- "4.6.0"
cache:
  directories:
  - node_modules
sudo: false
addons:
  postgresql: "9.4"
before_script:
- psql -c 'create database continua11y_test;' -U postgres
after_script:
- codeclimate-test-reporter < coverage/lcov.info
script: npm run test_coverage
after_script:
notifications:
  email: false
env:
  global:
  - GITHUB_TOKEN=FAKE_TEST_TOKEN
  - NODE_ENV=test
